version: "3.5"

services:
  backend:
    image: mysql:latest
    restart: always

    network_mode: host
    volumes:
      - ./data:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "2"
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command:
      "--max_connections=10000"
