subject:
  start_time: 2021-11-01T10:30
  end_time: 2022-11-21T10:30
  meta:
    establish_time: 1640153865.9001753
class:
  start_time: 2021-11-01T10:30
  end_time: 2021-11-21T10:30
  timeframe:
    first_year:
      start_time: 00:00:00
      end_time: '4:30:00'
    second_year:
      start_time: 04:30:00
      end_time: '9:00:00'
    third_year:
      start_time: 09:00:00
      end_time: '13:30:00'
    fourth_year:
      start_time: '14:30:00'
      end_time: '18:00:00'
    last_year:
      start_time: '18:00:00'
      end_time: '23:59:00'
  meta:
    establish_time: 1640153890.8168962
