subject:
  start_time: "2021-11-01 10:30:00"
  end_time: "2021-11-21 10:30:00"
  meta:
    establish_time: 1639837064.001687
class:
  start_time: "2021-11-01 10:30:00"
  end_time: "2022-11-01 10:30:00"
  timeframe:
    first_year:
      start_time: "00:00"
      end_time: '4:30'
    second_year:
      start_time: '4:30'
      end_time: '9:00'
    third_year:
      start_time: '9:00'
      end_time: '13:30'
    fourth_year:
      start_time: '13:30'
      end_time: '18:00'
    last_year:
      start_time: '18:00'
      end_time: '23:59'
  meta:
    establish_time: 1639837064.0036798
